replicaCount: 1

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

auth:
  rootUsername: root
  rootPassword: mysecurepassword

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}
