@startuml
scale 2
left to right direction
hide stereotype
skinparam DefaultTextAlignment center
skinparam ArrowThickness 1.3

actor User
package "Petstore Reference Deployment" {
  [core] as core
  [auth] as auth
  [monitor] as monitor
  [MongoDB] as db
}

User --> auth : Token generation
User --> core : Create/Read pets
User --> monitor : Read alarms
core --> db : Data persistence
core --> monitor : Event notification
core --> auth : Token validation
@enduml